# the name of your track or event
name = "Data And IPFS: Transfer"

# the name of the group organizing the event
org = ""

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@hannahhoward"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://ipfs-althing.io"

# the start date of the event
date = "2022-07-14"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 12:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "50"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
Part 2 of the "Data And IPFS" track will focus on content-addressed data transfer protocols, focusing on four key areas:

1. Multi-party data transfer
2. Efficient graph synchronization
3. connection integrity
4. connection saturation

"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="09:00"
speakers=["@hannahhoward"]
title="Welcome to the world of data transfer"
description="""
This is track introduction and facilitated discussion to:
1. Find out why we're here
2. Help folks get shared understanding on the overall problem space
3. Identify what we want to accomplish during the day
"""
# ^^ This is actually about 15 minutes of content, but it's 30 minutes to allow for starting late and staying on schedule

[[timeslots]]
startTime="09:30"
speakers=["@stebalien?"]
title="bitswap AMA"
description="stebalien is one of the keepers of 'human spec' on how bitswap works in practice. In this talk he'll give a brain dump of bitswap, and do a Q & A on the details"

[[timeslots]]
startTime="10:00"
speakers=["@hannah"]
title="Why everyone hates GraphSync, but maybe shouldn't"
description="""
Hannah will give an overview of Graphsync—how it works, what it can do in 2022. 
We'll also cover some challenges and why it is hard to make GraphSync work well.
"""

[[timeslots]]
startTime="10:30"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="10:45"
speakers=["@expede?", "@phillip?"]
title="CAR Pool: Multiparty dag sync with CAR files"
description=""

[[timeslots]]
startTime="11:15"
speakers=["@b5"]
title="What's in a manifest?"
description="This talk will define a common pattern found in graphsync, bittorrent, dsync, and CAR files: clients fetching an index of the content to optimize data transfer. We'll examine the benefits & drawbacks of this approach, and connect this back to the architecture of IPFS"

[[timeslots]]
startTime="11:30"
speakers=[]
title="Group Discussion: Data Transfer"
description="Let's talk about what we've learned and next steps"
