# the name of your track or event
name = "Data and IPFS: Unconf"

# the name of the group organizing the event
org = ""

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@hannahhoward+@aschmahmann"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = ""

# the start date of the event
date = "2022-07-14"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "50"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """

Part 3 of the "Data and IPFS" track is an unconference for any topics related to
either data models or data transfer on IPFS.

We may also schedule follow-ups to topics covered in either Part 1 or Part 2
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon

[[timeslots]]
startTime="13:00"
speakers=["@hannahhoward", "aschmahmann]
titles="Intro and Afternoon Planning"
description="""
Review what we has already been discussed in parts 1 and 2, and pitch topics.
Pitch a 10-15 minute discussion or claim two slots for 30 minutes.
"""

[[timeslots]]
startTime="13:30"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="13:45"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="14:00"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="14:15"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="14:30"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="14:45"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="15:00"
speakers=[]
titles="Break"
description=""

[[timeslots]]
startTime="15:15"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="15:30"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="15:45"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="16:00"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="16:15"
speakers=[]
titles="Open Slot"
description="TBD"

[[timeslots]]
startTime="16:30"
speakers=[]
titles="Report backs and closing"
description="""
Group discussions summarize learnings for everyone. Review overall learnings from
parts 1, 2, and 3 and discuss next steps
"""
